name: surl

services:
  server:
    build: ./
    depends_on:
      - db
    ports:
      - "8080:8080"
    networks:
      - surl-network
  db:
    image: postgres:16.2-alpine
    restart: always
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
    ports:
    - "${DB_PORT}:${DB_PORT}"
    volumes:
    - surl-data:/var/lib/postgresql/data
    - ./scripts/db/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - surl-network

volumes:
  surl-data:
    driver: local

networks:
  surl-network:
    driver: bridge